CREATE TABLE Stages(
        idStage              Int  Auto_increment  NOT NULL ,
        dateVisite           Date NOT NULL ,
        nomVisiteur          Varchar (50) NOT NULL ,    
        lieuRealisation      Varchar (30) NOT NULL ,
        deplacement          Bool NOT NULL ,
        frequenceDeplacement Varchar (20) NOT NULL ,
        modeDeplacement      Varchar (20) NOT NULL ,
        attFormReglement     Bool NOT NULL ,
        libelleAttFormReg    Varchar (30) NOT NULL ,
        visiteMedical        Bool NOT NULL ,
        travauxDang          Bool NOT NULL ,
        dateDeclarationDerog Date NOT NULL ,
        sujetStage           Text NOT NULL ,
        travauxRealises      Text NOT NULL ,
        satisfactionEnt      Int NOT NULL ,
        remarqueEnt          Text NOT NULL ,
        perspectiveEmb       Int NOT NULL ,
        repTravauxDang1      Int NOT NULL ,
        repTravauxDang2      Int NOT NULL ,
        repTravauxDang3      Int NOT NULL ,
        repTravauxDang4      Int NOT NULL ,
        repTravauxDang5      Int NOT NULL ,
        objectifPAE          Text NOT NULL ,
        repTravauxDang6      Int NOT NULL ,
        autreRepTravauxDang  Varchar (50) NOT NULL ,
        dateDebut            Date NOT NULL ,
        dateFin              Date NOT NULL ,
        idStagiaire          Int NOT NULL ,
        idTuteur             Int NOT NULL
	,CONSTRAINT Stages_PK PRIMARY KEY (idStage)

	,CONSTRAINT Stages_Stagiaires_FK FOREIGN KEY (idStagiaire) REFERENCES Stagiaires(idStagiaire)
	,CONSTRAINT Stages_Tuteurs0_FK FOREIGN KEY (idTuteur) REFERENCES Tuteurs(idTuteur)
)ENGINE=InnoDB;


CREATE TABLE horaires
(
        idStage              Int  Auto_increment  NOT NULL ,
        dateDebutStage       Date NOT NULL ,
        dateFinStage         Date NOT NULL ,
        horaireDebutJour1    Time NOT NULL ,
        horaireDebutJour2    Time NOT NULL ,
        horaireDebutJour3    Time NOT NULL ,
        horaireDebutJour4    Time NOT NULL ,
        horaireDebutJour5    Time NOT NULL ,
        horaireDebutJour6    Time NOT NULL ,
        horaireFinJour1      Time NOT NULL ,
        horaireFinJour2      Time NOT NULL ,
        horaireFinJour3      Time NOT NULL ,
        horaireFinJour4      Time NOT NULL ,
        horaireFinJour5      Time NOT NULL ,
        horaireFinJour6      Time NOT NULL ,
        horaireDebutDej1     Time NOT NULL ,
        horaireDebutDej2     Time NOT NULL ,
        horaireDebutDej3     Time NOT NULL ,
        horaireDebutDej4     Time NOT NULL ,
        horaireDebutDej5     Time NOT NULL ,
        horaireDebutDej6     Time NOT NULL ,
        horaireFinDej1       Time NOT NULL ,
        horaireFinDej2       Time NOT NULL ,
        horaireFinDej3       Time NOT NULL ,
        horaireFinDej4       Time NOT NULL ,
        horaireFinDej5       Time NOT NULL ,
        horaireFinDej6       Time NOT NULL 
)ENGINE=InnoDB;

CREATE TABLE evaluations
(
        idStage              Int  Auto_increment  NOT NULL ,
        dateEvaluation       Date NOT NULL ,
        objectifAcquisition  Int NOT NULL ,
        comportementMt       Int NOT NULL ,
        evalComportement     Char (1) NOT NULL ,
        libelleAcquis1       Varchar (50) NOT NULL ,
        libelleAcquis2       Varchar (50) NOT NULL ,
        libelleAcquis3       Varchar (50) NOT NULL ,
        libelleAcquis4       Varchar (50) NOT NULL ,
        libelleAcquis5       Varchar (50) NOT NULL ,
        libelleAcquis6       Varchar (50) NOT NULL ,
        libelleAcquis7       Varchar (50) NOT NULL ,
        libelleAcquis8       Varchar (50) NOT NULL ,
        libelleAcquis9       Varchar (50) NOT NULL ,
        libelleAcquis10      Varchar (50) NOT NULL ,
        acquis1              Int NOT NULL ,
        acquis2              Int NOT NULL ,
        acquis3              Int NOT NULL ,
        acquis4              Int NOT NULL ,
        acquis5              Int NOT NULL ,
        acquis6              Int NOT NULL ,
        acquis7              Int NOT NULL ,
        acquis8              Int NOT NULL ,
        acquis9              Int NOT NULL ,
        acquis10             Int NOT NULL ,
)ENGINE=InnoDB;